# Generated by Django 4.2.2 on 2023-08-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoBots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=100, unique=True)),
                ('bot_instance', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MartBotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=100)),
                ('api_secret', models.CharField(blank=True, max_length=100)),
                ('bot_name', models.CharField(blank=True, max_length=100)),
                ('total_profit', models.FloatField(default=0.0)),
                ('transactions', models.IntegerField(default=0)),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('symbol', models.CharField(max_length=100)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('trailing', models.FloatField(blank=True, null=True)),
                ('scale', models.JSONField(blank=True, null=True)),
                ('rebounce', models.JSONField(blank=True, null=True)),
                ('volume_list', models.JSONField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('orders', models.IntegerField(blank=True, null=True)),
                ('use', models.FloatField(blank=True, null=True)),
                ('bought', models.IntegerField(default=0)),
                ('buying', models.BooleanField(default=False)),
                ('selling', models.BooleanField(default=False)),
                ('trailing_buy_price', models.FloatField(blank=True, null=True)),
                ('recent_trailing_buy_price', models.FloatField(blank=True, null=True)),
                ('trailing_sell_price', models.FloatField(blank=True, null=True)),
                ('recent_trailing_sell_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
