# Generated by Django 4.2.1 on 2023-08-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='martbotstate',
            name='amount_bought',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='martbotstate',
            name='price_bought',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
