# Generated by Django 4.2.2 on 2023-07-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingorders',
            name='order_type',
            field=models.CharField(choices=[('BUY', 'Buy Order'), ('SELL', 'Sell Order')], default='SELL', max_length=4),
        ),
    ]
