# Generated by Django 4.2.2 on 2023-07-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebots', '0002_tradingorders_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoBots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=100, unique=True)),
                ('bot_instance_json', models.TextField()),
            ],
        ),
    ]
