# Generated by Django 4.2.1 on 2023-08-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradebots', '0004_remove_cryptobots_bot_instance_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('api_secret', models.CharField(max_length=100)),
                ('bot_name', models.CharField(max_length=100)),
                ('bot_type', models.CharField(choices=[('martbot', 'Martingale Bot'), ('gridbot', 'Grid Bot')], max_length=10)),
                ('total_profit', models.FloatField(max_length=15)),
            ],
            options={
                'unique_together': {('bot_name', 'bot_type')},
            },
        ),
        migrations.DeleteModel(
            name='TradingOrders',
        ),
        migrations.CreateModel(
            name='MartBotState',
            fields=[
                ('botstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tradebots.botstate')),
                ('bot_state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='martbot_state', serialize=False, to='tradebots.botstate')),
                ('transactions', models.IntegerField(default=0)),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('symbol', models.CharField(max_length=100)),
                ('profit', models.FloatField()),
                ('trailing', models.FloatField()),
                ('scale', models.JSONField()),
                ('rebounce', models.JSONField()),
                ('volume_list', models.JSONField()),
                ('volume', models.FloatField()),
                ('orders', models.IntegerField()),
                ('use', models.FloatField()),
                ('bought', models.IntegerField(default=0)),
                ('buying', models.BooleanField(default=False)),
                ('selling', models.BooleanField(default=False)),
                ('trailing_buy_price', models.FloatField(blank=True, null=True)),
                ('recent_trailing_buy_price', models.FloatField(blank=True, null=True)),
                ('trailing_sell_price', models.FloatField(blank=True, null=True)),
                ('recent_trailing_sell_price', models.FloatField(blank=True, null=True)),
            ],
            bases=('tradebots.botstate',),
        ),
    ]
