# Generated by Django 4.2.2 on 2023-08-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebots', '0006_alter_botstate_total_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martbotstate',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
