# Generated by Django 4.2.2 on 2023-08-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebots', '0007_alter_martbotstate_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martbotstate',
            name='orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='martbotstate',
            name='rebounce',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='martbotstate',
            name='scale',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='martbotstate',
            name='trailing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='martbotstate',
            name='use',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='martbotstate',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='martbotstate',
            name='volume_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
