# Generated by Django 4.2.2 on 2023-08-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradebots', '0008_alter_martbotstate_orders_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='botstate',
            unique_together={('bot_name',)},
        ),
    ]
